image: registry.gitlab.com/islandoftex/images/texlive:latest

compile_umlet:
  image: coenvl/umlet
  stage: build
  before_script:
  - apk update && apk add bash
  script:
    - chmod +x /Umlet/umlet.sh
    - chmod +x diagrams/compile.sh
    - bash diagrams/compile.sh
  artifacts:
    paths:
      - out

build:
  stage: build
  script:
    - cd latex/
    - sed -i 's/setboolean{DEBUG}{true}/setboolean{DEBUG}{false}/' main.tex
    - pdflatex main.tex
    - pdflatex main.tex
  after_script:
    - cat latex/main.log
    - mv latex/main.pdf main.pdf
  artifacts:
    paths:
      - main.pdf
